# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database.Post import Post as post
from functools import partial


class Ui_MainWindow(object):

    user = None
    dbConn = None

    def showPosts(self):
        posts = post.getAll(self.dbConn)

        for p in posts:
                self.post = QtWidgets.QFrame()
                self.post.setEnabled(True)
                self.post.setFixedSize(QtCore.QSize(500, 200))
                self.post.setStyleSheet("background-color: rgb(85, 255, 127);")
                self.post.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.post.setFrameShadow(QtWidgets.QFrame.Raised)
                self.post.setObjectName("post")
                self.userPhoto = QtWidgets.QLabel(self.post)
                self.userPhoto.setGeometry(QtCore.QRect(10, 10, 47, 41))
                self.userPhoto.setText("")
                self.userPhoto.setPixmap(QtGui.QPixmap("assets/defaultIcon.png"))
                self.userPhoto.setScaledContents(True)
                self.userPhoto.setObjectName("userPhoto")
                self.userName = QtWidgets.QLabel(self.post)
                self.userName.setGeometry(QtCore.QRect(70, 10, 47, 13))
                self.userName.setObjectName("userName")
                self.like = QtWidgets.QPushButton(self.post)
                self.like.setGeometry(QtCore.QRect(460, 170, 31, 23))
                self.like.setStyleSheet("color: rgb(255, 0, 0);\n"
        "background-color: rgb(255, 255, 255);")
                self.like.setObjectName("like")
                self.postContent = QtWidgets.QLabel(self.post)
                self.postContent.setGeometry(QtCore.QRect(10, 60, 481, 101))
                self.postContent.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
                self.postContent.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.postContent.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.postContent.setScaledContents(False)
                self.postContent.setWordWrap(False)
                self.postContent.setObjectName("postContent")
                self.userName.setText(p[2])
                self.like.setText("❤")
                self.postContent.setText(p[1])
                self.postsLayout.addWidget(self.post)


    def myConfig(self, MainWindow):
            MainWindow.setFixedSize(1024, 768)
            self.username.setText(self.user[0])
            self.sendPost.clicked.connect(partial(post.send, self.dbConn, self.user[0], self.postTitle, self.postText))

    def setupUi(self, MainWindow, dbConn, user):

        self.user = user
        self.dbConn = dbConn

        #################################################### QT DESIGNER ###############################################

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sideBar = QtWidgets.QWidget(self.centralwidget)
        self.sideBar.setGeometry(QtCore.QRect(0, 0, 281, 771))
        self.sideBar.setAutoFillBackground(False)
        self.sideBar.setStyleSheet("background-color: rgb(255, 65, 255);\n"
"border: 2px double rgb(0, 0, 0);")
        self.sideBar.setObjectName("sideBar")
        self.profilePhoto = QtWidgets.QLabel(self.sideBar)
        self.profilePhoto.setGeometry(QtCore.QRect(36, 150, 211, 201))
        self.profilePhoto.setStyleSheet("")
        self.profilePhoto.setText("")
        self.profilePhoto.setPixmap(QtGui.QPixmap("assets/defaultIcon.png"))
        self.profilePhoto.setScaledContents(True)
        self.profilePhoto.setObjectName("profilePhoto")
        self.options = QtWidgets.QWidget(self.sideBar)
        self.options.setGeometry(QtCore.QRect(30, 380, 221, 281))
        self.options.setStyleSheet("background-color: rgb(156, 11, 154);\n"
"border: none;")
        self.options.setObjectName("options")
        self.pushButton = QtWidgets.QPushButton(self.options)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 221, 51))
        self.pushButton.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.options)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 80, 221, 51))
        self.pushButton_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.options)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 150, 221, 51))
        self.pushButton_3.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.options)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 220, 221, 51))
        self.pushButton_4.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.username = QtWidgets.QLabel(self.sideBar)
        self.username.setGeometry(QtCore.QRect(10, 60, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(30)
        self.username.setFont(font)
        self.username.setStyleSheet("border: none")
        self.username.setScaledContents(False)
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.background.setFont(font)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("assets/mainBackground.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(420, 20, 461, 241))
        self.frame.setStyleSheet("border: 2px solid rgb(98, 106, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.postText = QtWidgets.QTextEdit(self.frame)
        self.postText.setGeometry(QtCore.QRect(40, 110, 381, 71))
        self.postText.setStyleSheet("border: 1px solid;")
        self.postText.setObjectName("postText")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 25, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none")
        self.label.setObjectName("label")
        self.sendPost = QtWidgets.QPushButton(self.frame)
        self.sendPost.setGeometry(QtCore.QRect(350, 190, 71, 41))
        self.sendPost.setStyleSheet("border: 1px solid;")
        self.sendPost.setObjectName("sendPost")
        self.postTitle = QtWidgets.QLineEdit(self.frame)
        self.postTitle.setGeometry(QtCore.QRect(40, 80, 381, 20))
        self.postTitle.setObjectName("postTitle")
        self.postsPanel = QtWidgets.QScrollArea(self.centralwidget)
        self.postsPanel.setGeometry(QtCore.QRect(299, 279, 711, 471))
        self.postsPanel.setWidgetResizable(True)
        self.postsPanel.setAlignment(QtCore.Qt.AlignCenter)
        self.postsPanel.setObjectName("postsPanel")
        self.posts = QtWidgets.QWidget()
        self.posts.setGeometry(QtCore.QRect(0, 0, 709, 469))
        self.posts.setObjectName("posts")
        self.postsLayout = QtWidgets.QVBoxLayout(self.posts)
        self.postsLayout.setContentsMargins(50, 0, 0, 0)
        self.postsLayout.setObjectName("postsLayout")
        self.postsPanel.setWidget(self.posts)
        MainWindow.setCentralWidget(self.centralwidget)



        #################################################################################################################

        self.myConfig(MainWindow)
        self.showPosts()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.background.raise_()
        self.sideBar.raise_()
        self.frame.raise_()
        self.postsPanel.raise_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Perfil"))
        self.pushButton_2.setText(_translate("MainWindow", "Chat"))
        self.pushButton_3.setText(_translate("MainWindow", "Configurações"))
        self.pushButton_4.setText(_translate("MainWindow", "Sobre"))
        self.username.setText(_translate("MainWindow", self.user[0]))
        self.label.setText(_translate("MainWindow", "Como está se sentindo ? Quais são as novidades ?"))
        self.sendPost.setText(_translate("MainWindow", "Enviar"))