# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import views.Profile as Profile
import views.CommentsFrame as Comments
from PyQt5 import QtCore, QtGui, QtWidgets
from database.Post import Post as post
from tools.Session import Session
import views.Login as Login
from functools import partial


class Ui_MainWindow(QtWidgets.QMainWindow):

    user = None
    dbConn = None
    thisWindow = None

    def logout(self):
        Session.closeSession()

        self.LoginWindow = QtWidgets.QMainWindow()
        ui = Login.Ui_LoginWindow()
        ui.setupUi(self.LoginWindow, self.dbConn)
        self.LoginWindow.show()
        self.thisWindow.close()

    def reload_posts(self, layout):
        while layout.count():
            child = layout.takeAt(0)
            if child.widget() is not None:
                child.widget().deleteLater()
            elif child.layout() is not None:
                self.clearTasks(child.layout(), None)

    def open_profile(self, event):
        self.thisWindow.close()
        
        self.ProfileWindow = QtWidgets.QMainWindow()
        ui = Profile.Ui_ProfileWindow()
        ui.setupUi(self.ProfileWindow, self.dbConn, self.user)
        self.ProfileWindow.show()

    def like_post(self, likeButton, thePost, theUser, event):
        currentAmount = likeButton.text().split(" ")[1]
        post.send_like(self.dbConn, thePost, theUser);
        likeButton.setText("❤" + " " + str(int(currentAmount) + 1))

    def comment_post(self, commentButton, thePost, theUser, event):
        self.comment_frame = Comments.CommentsFrame(self.centralwidget, self.dbConn, theUser, thePost)
        self.comment_frame.show()

    def show_posts(self):
        posts = post.get_all(self.dbConn)

        for p in posts:
            self.post = QtWidgets.QFrame()
            self.post.setEnabled(True)
            self.post.setFixedSize(QtCore.QSize(500, 200))
            self.post.setStyleSheet("background-color: rgb(85, 255, 127);")
            self.post.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.post.setFrameShadow(QtWidgets.QFrame.Raised)
            self.post.setObjectName("post")
            self.userPhoto = QtWidgets.QLabel(self.post)
            self.userPhoto.setGeometry(QtCore.QRect(10, 10, 47, 41))
            self.userPhoto.setText("")
            self.userPhoto.setPixmap(QtGui.QPixmap("assets/defaultIcon.png"))
            self.userPhoto.setScaledContents(True)
            self.userPhoto.setObjectName("userPhoto")
            self.userName = QtWidgets.QLabel(self.post)
            self.userName.setGeometry(QtCore.QRect(70, 10, 47, 13))
            self.userName.setObjectName("userName")
            self.like = QtWidgets.QPushButton(self.post)
            self.like.setGeometry(QtCore.QRect(420, 170, 31, 23))
            self.like.setStyleSheet("color: rgb(255, 0, 0);\n"
        "background-color: rgb(255, 255, 255);")
            self.like.setObjectName("like")
            self.comment = QtWidgets.QPushButton(self.post)
            self.comment.setGeometry(QtCore.QRect(460, 170, 31, 23))
            self.comment.setStyleSheet("color: rgb(255, 0, 0);\n"
                                    "background-color: rgb(255, 255, 255);")
            self.comment.setObjectName("like")
            self.postTitle_ = QtWidgets.QLabel(self.post)
            self.postTitle_.setGeometry(QtCore.QRect(10, 55, 481, 21))
            self.postTitle_.setText(p[2]);
            self.postTitle_.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
            self.postTitle_.setLayoutDirection(QtCore.Qt.LeftToRight)
            self.postTitle_.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.postTitle_.setScaledContents(False)
            self.postTitle_.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
            self.postTitle_.setWordWrap(False)
            self.postTitle_.setObjectName("postTitle_")
            self.postContent = QtWidgets.QLabel(self.post)
            self.postContent.setGeometry(QtCore.QRect(10, 80, 481, 81))
            self.postContent.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
            self.postContent.setLayoutDirection(QtCore.Qt.LeftToRight)
            self.postContent.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.postContent.setScaledContents(False)
            self.postContent.setWordWrap(False)
            self.postContent.setObjectName("postContent")

            if p[1][2] != b'NULL':
                photoForAuthorPost = QtGui.QPixmap() 
                photoForAuthorPost.loadFromData(p[1][2])

                self.userPhoto.setPixmap(photoForAuthorPost)
                
            self.userName.setText(p[1][1])
            self.like.setText("❤" + " " + str(p[4]))
            self.like.clicked.connect(partial(self.like_post, self.like, p[0], self.user[0]))
            self.comment.setText("💬" + " " + str(p[5]))
            self.comment.clicked.connect(partial(self.comment_post, self.comment, p[0], self.user[0]))
            self.postContent.setText(p[3])
            self.postsLayout.addWidget(self.post)

    def sendYourPost(self):
        author = self.user[0]
        title = self.postTitle.text()
        content = self.postText.toPlainText()

        result = post.send(self.dbConn, author, title, content)

        if result == 'OK':
            QtWidgets.QMessageBox.about(self, 'Postado', 'Seu post foi enviado!')

            self.reload_posts(self.postsLayout)
            self.show_posts()

    def additional_config(self, MainWindow):
        MainWindow.setFixedSize(1024, 768)
        self.logoutButton.clicked.connect(partial(self.logout))
        self.sendPost.clicked.connect(partial(self.sendYourPost))
        self.toProfile.mousePressEvent = partial(self.open_profile)

    def setupUi(self, MainWindow, dbConn, user):

        self.thisWindow = MainWindow
        self.user = user
        self.dbConn = dbConn

        #################################################### QT DESIGNER ###############################################

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sideBar = QtWidgets.QWidget(self.centralwidget)
        self.sideBar.setGeometry(QtCore.QRect(0, 0, 281, 771))
        self.sideBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sideBar.setAutoFillBackground(False)
        self.sideBar.setStyleSheet("background-color: rgb(255, 65, 255);\n"
"border: 2px double rgb(0, 0, 0);")
        self.sideBar.setObjectName("sideBar")
        self.profilePhoto = QtWidgets.QLabel(self.sideBar)
        self.profilePhoto.setGeometry(QtCore.QRect(36, 150, 211, 201))
        self.profilePhoto.setStyleSheet("border: none")
        self.profilePhoto.setText("")
        self.profilePhoto.setPixmap(QtGui.QPixmap("assets/defaultIcon.png"))
        self.profilePhoto.setScaledContents(True)
        self.profilePhoto.setObjectName("profilePhoto")
        self.options = QtWidgets.QWidget(self.sideBar)
        self.options.setGeometry(QtCore.QRect(30, 380, 221, 281))
        self.options.setStyleSheet("background-color: rgb(156, 11, 154);\n"
"border: none;")
        self.options.setObjectName("options")
        self.toProfile = QtWidgets.QPushButton(self.options)
        self.toProfile.setGeometry(QtCore.QRect(10, 10, 201, 51))
        self.toProfile.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.toProfile.setObjectName("toProfile")
        self.toChat = QtWidgets.QPushButton(self.options)
        self.toChat.setGeometry(QtCore.QRect(10, 80, 201, 51))
        self.toChat.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.toChat.setObjectName("toChat")
        self.toSettings = QtWidgets.QPushButton(self.options)
        self.toSettings.setGeometry(QtCore.QRect(10, 150, 201, 51))
        self.toSettings.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.toSettings.setObjectName("toSettings")
        self.about = QtWidgets.QPushButton(self.options)
        self.about.setGeometry(QtCore.QRect(10, 220, 201, 51))
        self.about.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.about.setObjectName("about")
        self.username = QtWidgets.QLabel(self.sideBar)
        self.username.setGeometry(QtCore.QRect(10, 60, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(30)
        self.username.setFont(font)
        self.username.setStyleSheet("border: none")
        self.username.setScaledContents(False)
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.logoutButton = QtWidgets.QPushButton(self.sideBar)
        self.logoutButton.setGeometry(QtCore.QRect(210, 680, 41, 31))
        self.logoutButton.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.logoutButton.setObjectName("logoutButton")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.background.setFont(font)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("assets/mainBackground.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(420, 20, 461, 241))
        self.frame.setStyleSheet("border: 2px solid rgb(98, 106, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.postText = QtWidgets.QTextEdit(self.frame)
        self.postText.setGeometry(QtCore.QRect(40, 110, 381, 71))
        self.postText.setStyleSheet("border: 1px solid;")
        self.postText.setObjectName("postText")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 25, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none")
        self.label.setObjectName("label")
        self.sendPost = QtWidgets.QPushButton(self.frame)
        self.sendPost.setGeometry(QtCore.QRect(350, 190, 71, 41))
        self.sendPost.setStyleSheet("border: 1px solid;")
        self.sendPost.setObjectName("sendPost")
        self.postTitle = QtWidgets.QLineEdit(self.frame)
        self.postTitle.setGeometry(QtCore.QRect(40, 80, 381, 20))
        self.postTitle.setObjectName("postTitle")
        self.postsPanel = QtWidgets.QScrollArea(self.centralwidget)
        self.postsPanel.setGeometry(QtCore.QRect(299, 279, 711, 471))
        self.postsPanel.setWidgetResizable(True)
        self.postsPanel.setAlignment(QtCore.Qt.AlignCenter)
        self.postsPanel.setObjectName("postsPanel")
        self.posts = QtWidgets.QWidget()
        self.posts.setGeometry(QtCore.QRect(0, 0, 709, 469))
        self.posts.setObjectName("posts")
        self.postsLayout = QtWidgets.QVBoxLayout(self.posts)
        self.postsLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.postsLayout.setContentsMargins(50, 0, 0, 0)
        self.postsLayout.setObjectName("postsLayout")
        self.postsPanel.setWidget(self.posts)
        self.background.raise_()
        self.sideBar.raise_()
        self.frame.raise_()
        self.postsPanel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)




        #################################################################################################################

        self.additional_config(MainWindow)
        self.show_posts()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.background.raise_()
        self.sideBar.raise_()
        self.frame.raise_()
        self.postsPanel.raise_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toProfile.setText(_translate("MainWindow", "Perfil"))
        self.toChat.setText(_translate("MainWindow", "Chat"))
        self.toSettings.setText(_translate("MainWindow", "Configurações"))
        self.about.setText(_translate("MainWindow", "Sobre"))
        self.username.setText(_translate("MainWindow", self.user[1]))
        self.logoutButton.setText(_translate("MainWindow", "❌"))
        self.label.setText(_translate("MainWindow", "Como está se sentindo ? Quais são as novidades ?"))
        self.sendPost.setText(_translate("MainWindow", "Enviar"))

        if self.user[2] != b'NULL':
            imageForProfile = QtGui.QPixmap()
            imageForProfile.loadFromData(self.user[2])
            self.profilePhoto.setPixmap(imageForProfile)