# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import views.Home as Home
from database.User import User
from tools.Session import Session
from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial


class Ui_ProfileWindow(QtWidgets.QMainWindow):
    dbConn = None
    user = None
    thisWindow = None
    changes = {'username': False, 'password': False}


    def updateProfile(self):
        username = self.username.text()
        password = self.password.text()

        data = {'username': username, 'password': password}

        result = User.update(self.dbConn, data, self.user[0])

        if result == 'OK':
            self.user = [username, password]
            QtWidgets.QMessageBox.about(self, 'Sucesso', 'Perfil Atualizado!')
            Session.saveSession(self.user[0] + '|' + self.user[1])

    def checkChanges(self, fieldName, change):
        if fieldName == 'username':
            if self.user[0] == change:
                self.changes['username'] = False
            else:
                self.changes['username'] = True
        elif fieldName == 'password':
            if self.user[1] == change:
                self.changes['password'] = False
            else:
                self.changes['password'] = True

        if self.changes['username'] or self.changes['password']:
            self.update.setEnabled(True)
        else:
            self.update.setEnabled(False)

    def backToHome(self, event):
        self.thisWindow.close()
        self.HomeWindow = QtWidgets.QMainWindow()
        ui = Home.Ui_MainWindow()
        ui.setupUi(self.HomeWindow, self.dbConn, self.user)
        self.HomeWindow.show()

    def setupUi(self, MainWindow, dbConn, user):
        self.dbConn = dbConn
        self.user = user
        self.thisWindow = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 634)
        MainWindow.setStyleSheet("background-color: rgb(255, 138, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.profilePhoto = QtWidgets.QLabel(self.centralwidget)
        self.profilePhoto.setGeometry(QtCore.QRect(300, 40, 211, 191))
        self.profilePhoto.setText("")
        self.profilePhoto.setPixmap(QtGui.QPixmap("assets/defaultIcon.png"))
        self.profilePhoto.setScaledContents(True)
        self.profilePhoto.setObjectName("profilePhoto")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(150, 280, 101, 31))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(150, 340, 101, 31))
        self.label_password.setObjectName("label_password")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(250, 279, 321, 31))
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(250, 340, 321, 31))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setDragEnabled(True)
        self.password.setObjectName("password")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.backButton.setObjectName("backButton")
        self.backButton.clicked.connect(partial(self.backToHome))
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setEnabled(False)
        self.update.setGeometry(QtCore.QRect(730, 590, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.update.setFont(font)
        self.update.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update.setObjectName("update")
        MainWindow.setCentralWidget(self.centralwidget)


        self.username.setText(user[0])
        self.password.setText(user[1])
        self.username.textChanged.connect(partial(self.checkChanges, 'username'));
        self.password.textChanged.connect(partial(self.checkChanges, 'password'));
        self.update.clicked.connect(partial(self.updateProfile))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_username.setText(_translate("MainWindow", "Nome de usuário:"))
        self.label_password.setText(_translate("MainWindow", "Senha:"))
        self.backButton.setText(_translate("MainWindow", "☚"))
        self.update.setText(_translate("MainWindow", "Atualizar"))