# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import views.Home as Home
from database.User import User
from tools.Session import Session
from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
from PIL import Image
import os


class Ui_ProfileWindow(QtWidgets.QMainWindow):
    dbConn = None
    user = None
    thisWindow = None
    selectedProfilePhoto = ''
    changes = {'profilePhoto': False, 'displayName': False, 'password': False}

    def readPhotoData(self):
        if self.selectedProfilePhoto != '':
            photoData = open(self.selectedProfilePhoto, 'rb').read()
            return photoData
        else:
            return ''

    def selectNewProfilePhoto(self, event):
        file = QtWidgets.QFileDialog.getOpenFileName(self, "Open file", os.environ["HOMEPATH"] + "\\Desktop","Image files (*.jpg *.png)")

        if file[0] != '':
            self.selectedProfilePhoto = file[0]
            self.profilePhoto.setPixmap(QtGui.QPixmap(file[0]))
            self.changes['profilePhoto'] = True

            self.checkChanges('', '')


    def updateProfile(self):
        profilePhoto = self.readPhotoData()
        displayName = self.displayName.text()
        password = self.password.text()

        data = {'profilePhoto': profilePhoto, 'displayName': displayName, 'password': password}

        result = User.update(self.dbConn, data, self.user[0])

        if result == 'OK':
            self.user = [self.user[0], displayName, profilePhoto, password]
            QtWidgets.QMessageBox.about(self, 'Sucesso', 'Perfil Atualizado!')
            Session.saveSession(self.user[0] + '|' + self.user[3])

    def checkChanges(self, fieldName, change):
        if fieldName == 'displayName':
            if self.user[1] == change:
                self.changes['displayName'] = False
            else:
                self.changes['displayName'] = True
        elif fieldName == 'password':
            if self.user[2] == change:
                self.changes['password'] = False
            else:
                self.changes['password'] = True

        if self.changes['profilePhoto'] or self.changes['displayName'] or self.changes['password']:
            self.update.setEnabled(True)
        else:
            self.update.setEnabled(False)

    def backToHome(self, event):
        self.thisWindow.close()
        self.HomeWindow = QtWidgets.QMainWindow()
        ui = Home.Ui_MainWindow()
        ui.setupUi(self.HomeWindow, self.dbConn, self.user)
        self.HomeWindow.show()

    def setupUi(self, MainWindow, dbConn, user):
        self.dbConn = dbConn
        self.user = user
        self.thisWindow = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 634)
        MainWindow.setStyleSheet("background-color: rgb(255, 138, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.profilePhoto = QtWidgets.QLabel(self.centralwidget)
        self.profilePhoto.setGeometry(QtCore.QRect(300, 40, 211, 191))
        self.profilePhoto.setText("")
        self.profilePhoto.setPixmap(QtGui.QPixmap("assets/defaultIcon.png"))
        self.profilePhoto.setScaledContents(True)
        self.profilePhoto.setObjectName("profilePhoto")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(150, 280, 101, 31))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(150, 400, 101, 31))
        self.label_password.setObjectName("label_password")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setEnabled(False)
        self.username.setGeometry(QtCore.QRect(250, 279, 321, 31))
        self.username.setStyleSheet("\n"
"background-color: rgb(197, 197, 197);")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(250, 400, 321, 31))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setDragEnabled(True)
        self.password.setObjectName("password")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.backButton.setObjectName("backButton")
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setEnabled(False)
        self.update.setGeometry(QtCore.QRect(730, 590, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.update.setFont(font)
        self.update.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update.setObjectName("update")
        self.label_displayName = QtWidgets.QLabel(self.centralwidget)
        self.label_displayName.setGeometry(QtCore.QRect(150, 340, 101, 31))
        self.label_displayName.setObjectName("label_displayName")
        self.displayName = QtWidgets.QLineEdit(self.centralwidget)
        self.displayName.setEnabled(True)
        self.displayName.setGeometry(QtCore.QRect(250, 340, 321, 31))
        self.displayName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.displayName.setText("")
        self.displayName.setObjectName("displayName")
        MainWindow.setCentralWidget(self.centralwidget)


        self.username.setText(user[0])
        self.displayName.setText(user[1])

        if self.user[2] != None:
            imageForProfile = QtGui.QPixmap()
            imageForProfile.loadFromData(self.user[2])
            self.profilePhoto.setPixmap(imageForProfile)
        
        self.password.setText(user[3])

        self.profilePhoto.mousePressEvent = partial(self.selectNewProfilePhoto)
        self.displayName.textChanged.connect(partial(self.checkChanges, 'displayName'));
        self.password.textChanged.connect(partial(self.checkChanges, 'password'));
        self.backButton.clicked.connect(partial(self.backToHome))
        self.update.clicked.connect(partial(self.updateProfile))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_username.setText(_translate("MainWindow", "Nome de usuário:"))
        self.label_password.setText(_translate("MainWindow", "Senha:"))
        self.backButton.setText(_translate("MainWindow", "☚"))
        self.update.setText(_translate("MainWindow", "Atualizar"))
        self.label_displayName.setText(_translate("MainWindow", "Nome de exibição:"))