# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
import views.Login as Login
from database.User import User


class Ui_RegisterWindow(object):
    dbConn = None
    this_window = None
    selected_image = 'NULL'

    def register_user(self):
        username = self.username.text()
        display_name = self.display_name.text()
        profile_photo = self.read_photo_data()
        password = self.password.text()

        user_data = {'username': username, 'display_name': display_name, 'profile_photo': profile_photo, 'password': password}

        operation_response = User.insert(self.dbConn, user_data)

        if operation_response == 'OK':
            QtWidgets.QMessageBox.about(self.this_window, 'Sucesso', 'Usuário cadastrado!')
            self.go_to_login_window(self.this_window, None)
        elif operation_response == 'DUPLICATE_KEY':
            QtWidgets.QMessageBox.about(self.this_window, 'Erro', 'Nome de usuário já existente!')
            self.username.setText('')

    def read_photo_data(self):
        if self.selected_image != 'NULL':
            try:
                photo_data = open(self.selected_image, 'rb').read()
            except FileNotFoundError:
                photo_data = 'NULL'

            return photo_data
        else:
            return 'NULL'

    def change_profile_photo(self, event):
        file = QtWidgets.QFileDialog.getOpenFileName(self.this_window, "Open file", os.environ["HOMEPATH"] + "\\Desktop",
                                                     "Image files (*.jpg *.png)")

        if file[0] != '':
            self.selected_image = file[0]
            self.profilePhoto.setPixmap(QtGui.QPixmap(self.selected_image))

    def go_to_login_window(self, RegisterWindow, event):
        self.login_window = QtWidgets.QMainWindow()
        self.login_ui = Login.Ui_LoginWindow()
        self.login_ui.setupUi(self.login_window, self.dbConn)
        self.login_window.show()
        RegisterWindow.close()

    def additional_config(self, RegisterWindow):
        RegisterWindow.setFixedSize(1024, 768)
        self.goLogin.mousePressEvent = partial(self.go_to_login_window, RegisterWindow)
        self.pushButton.clicked.connect(partial(self.register_user))
        self.profilePhoto.mousePressEvent = self.change_profile_photo

    def setup_ui(self, RegisterWindow, conn):
        self.dbConn = conn
        self.this_window = RegisterWindow

        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.setWindowModality(QtCore.Qt.NonModal)
        RegisterWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RegisterWindow.sizePolicy().hasHeightForWidth())
        RegisterWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("assets/authBackground.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setGeometry(QtCore.QRect(330, 280, 411, 411))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.container.setPalette(palette)
        self.container.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.label_username = QtWidgets.QLabel(self.container)
        self.label_username.setGeometry(QtCore.QRect(60, 180, 101, 61))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.container)
        self.label_password.setGeometry(QtCore.QRect(60, 270, 101, 51))
        self.label_password.setObjectName("label_password")
        self.username = QtWidgets.QLineEdit(self.container)
        self.username.setGeometry(QtCore.QRect(170, 200, 220, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.container)
        self.password.setGeometry(QtCore.QRect(170, 290, 220, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pushButton = QtWidgets.QPushButton(self.container)
        self.pushButton.setGeometry(QtCore.QRect(300, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.error = QtWidgets.QLabel(self.container)
        self.error.setGeometry(QtCore.QRect(150, 390, 251, 16))
        self.error.setStyleSheet("color: rgb(255, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.profilePhoto = QtWidgets.QLabel(self.container)
        self.profilePhoto.setGeometry(QtCore.QRect(130, 10, 161, 131))
        self.profilePhoto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profilePhoto.setText("")
        self.profilePhoto.setPixmap(QtGui.QPixmap("assets/defaultIcon.png"))
        self.profilePhoto.setScaledContents(True)
        self.profilePhoto.setObjectName("profilePhoto")
        self.display_name = QtWidgets.QLineEdit(self.container)
        self.display_name.setGeometry(QtCore.QRect(170, 250, 220, 20))
        self.display_name.setText("")
        self.display_name.setObjectName("display_name")
        self.display_name_label = QtWidgets.QLabel(self.container)
        self.display_name_label.setGeometry(QtCore.QRect(60, 230, 101, 51))
        self.display_name_label.setObjectName("display_name_label")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(330, 170, 411, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(6, 52, 113);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.goLogin = QtWidgets.QLabel(self.centralwidget)
        self.goLogin.setGeometry(QtCore.QRect(10, 10, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.goLogin.setFont(font)
        self.goLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goLogin.setWordWrap(False)
        self.goLogin.setObjectName("goLogin")
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.additional_config(RegisterWindow)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Login"))
        self.label_username.setText(_translate("RegisterWindow", "Nome de usuário:"))
        self.label_password.setText(_translate("RegisterWindow", "Senha:"))
        self.pushButton.setText(_translate("RegisterWindow", "👉🏻"))
        self.display_name_label.setText(_translate("RegisterWindow", "Nome de exibição:"))
        self.title.setText(_translate("RegisterWindow", "Register"))
        self.goLogin.setText(_translate("RegisterWindow", "Back to Login Screen"))
